apiVersion: v1
kind: ReplicationController
metadata:
  name: echoheaders
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      selector:
        app: echoheaders
      containers:
        - name: echoheaders
          image: k8s.gcr.io/echoserver:1.10
          ports:
            - containerPort: 8080
